name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Navigate to the project directory
            cd /root/nimet-adl

            # Fetch latest changes
            git pull origin main

            # Update Backend dependencies and restart PM2
            npm install --production
            pm2 restart nimet-adl-backend

            # Update Frontend dependencies and rebuild React app
            cd frontend
            npm install
            npm run build
